config/routes.rb
Rails.application.routes.draw do
  get 'projectile/free_fall'
  post 'projectile/free_fall'

  get 'projectile/projectile'
  post 'projectile/projectile'

  get 'index/index'

  get 'length_contraction/length_contraction'
  post 'length_contraction/length_contraction'

  get 'time_dilation/time_dilation'
  post 'time_dilation/time_dilation'

  get 'main/main'

  root 'main#main'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cosmology_controller.rb
class CosmologyController < ApplicationController
  def cosmology
  end

  def brief_history
  end
end

app/controllers/doppler_shift_controller.rb
class DopplerShiftController < ApplicationController
  def doppler_shift
    f_0 = params[:frequendy].to_f
    @b = params[:velocity].to_f/299792458.0
    @dt_p = t_0/(Math.sqrt(1-(@b**2)))
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/length_contraction_controller.rb
class LengthContractionController < ApplicationController

  def length_contraction
    unit = params[:units].to_i
    if unit == 1
      l_0 = params[:length].to_f
      b = params[:velocity].to_f/299792458.0
      @dl = l_0*(Math.sqrt(1-(b**2)))
    elsif unit == 2
      l_0 = params[:length].to_f
      b = params[:velocity].to_f/670616629.0
      @dl = l_0*(Math.sqrt(1-(b**2)))
    elsif unit == 3
      l_0 = params[:length].to_f
      b = params[:velocity].to_f/1079252850.0
      @dl = l_0*(Math.sqrt(1-(b**2)))
    elsif unit == 4
      l_0 = params[:length].to_f
      b = params[:velocity].to_f
      @dl = l_0*(Math.sqrt(1-(b**2)))
    end
    #render 'time_dilation'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def main
  end
end

app/controllers/projectile_controller.rb
class ProjectileController < ApplicationController

  G = 9.81

  # Need to get x_0, v_0, t_0, total_time
  def free_fall
    dt = 0.1
    x_0 = params[:x_0].to_f
    v_0 = params[:v_0].to_f
    t_0 = params[:t_0].to_f
    @x_t = []

    # Time to hit the ground?
    @hit = Math.sqrt((2*x_0)/G)

    (0..@hit.round(1)).step(dt) do |t|
      x = -0.5*G*(t**2) + v_0*t + x_0
      @x_t << [t.round(2), x.round(3)]
    end

    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(:height => '300')
      f.series(:type => 'scatter', :name =>
          'Free Fall Motion',
               data: @x_t, :color => '#00463f')
      f.plotOptions({line: {enableMouseTracking: false}})
      f.legend({:align => 'center', :verticalAlign=> 'top',
                :y => 0, :borderWidth => 0, style: {color: "#333"}})
    end
  end

  def projectile
    dt = 0.1
    x_0 = params[:x_0].to_f
    y_0 = params[:y_0].to_f
    v_0 = params[:v_0].to_f
    angle = params[:angle].to_f
    @x_y = []

    # Max height
    @y_max = ((v_0**2)*(Math.sin(angle))**2)/(2*G)

    # Time of flight
    @tof = (2*v_0*Math.sin(angle))/G

    @tof_gen = (v_0*Math.sin(angle)+Math.sqrt(2*G*y_0 + (v_0**2)*(Math.sin(angle))**2))/G

    # Maximum distance of the projectile
    @distance = ((v_0**2)/G)*Math.sin(2*angle)

    # Data for plot
    v_x = v_0*Math.cos(angle)
    v_y = v_0*Math.sin(angle)

    (0..@tof_gen.round(1)).step(dt) do |t|
      x = v_x*t + x_0
      y = v_y*t -0.5*G*(t**2) + y_0

      @x_y << [x.round(2), y.round(2)]
    end

    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(:height => '300')
      f.series(:type => 'scatter', :name =>
          'Projectile Motion',
               data: @x_y, :color => '#00463f')
      f.plotOptions({line: {enableMouseTracking: false}})
      f.legend({:align => 'center', :verticalAlign=> 'top',
                :y => 0, :borderWidth => 1, style: {color: "#333"}})
      end

  end

end

app/controllers/time_dilation_controller.rb
class TimeDilationController < ApplicationController

  def time_dilation
    unit = params[:units].to_i
    if unit == 1
      t_0 = params[:delta_t].to_f
      @b = params[:velocity].to_f/299792458.0
      @dt_p = t_0/(Math.sqrt(1-(@b**2)))
      @u = 'm/s'
    elsif unit == 2
      t_0 = params[:delta_t].to_f
      @b = params[:velocity].to_f/670616629.0
      @dt_p = t_0/(Math.sqrt(1-(@b**2)))
      @u = 'mph'
    elsif unit == 3
      t_0 = params[:delta_t].to_f
      @b = params[:velocity].to_f/1079252850.0
      @dt_p = t_0/(Math.sqrt(1-(@b**2)))
      @u = 'kph'
    elsif unit == 4
      t_0 = params[:delta_t].to_f
      @b = params[:velocity].to_f
      @dt_p = t_0/(Math.sqrt(1-(@b**2)))
      @u = 'c'
    end

    #render 'time_dilation'
  end

end

app/controllers/universe_history_controller.rb
class UniverseHistoryController < ApplicationController
  def universe_history
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cosmology_helper.rb
module CosmologyHelper
end

app/helpers/doppler_shift_helper.rb
module DopplerShiftHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/length_contraction_helper.rb
module LengthContractionHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projectile_helper.rb
module ProjectileHelper
end

app/helpers/time_dilation_helper.rb
module TimeDilationHelper
end

app/helpers/universe_history_helper.rb
module UniverseHistoryHelper
end

app/views/cosmology/brief_history.html.erb
<head xmlns="http://www.w3.org/1999/html">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <title>Time Dilation</title>
</head>

<body>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="1200px-CMB_Timeline300_no_WMAP.jpg" alt="First caption">
      <div class="carousel-caption">
        Here is a test caption 01
      </div>
    </div>
    <div class="item">
      <img src="..." alt="Second Caption">
      <div class="carousel-caption">
        Here is the second slide
      </div>
    </div>
    TEST TEST TEST
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</body>

app/views/cosmology/cosmology.html.erb
<h1>Cosmology#cosmology</h1>
<p>Find me in app/views/cosmology/cosmology.html.erb</p>

app/views/doppler_shift/doppler_shift.html.erb
<head xmlns="http://www.w3.org/1999/html">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

  <%= stylesheet_link_tag "time_dilation.css.scss" %>

  <title>The Doppler Effect</title>
</head>

<body>
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <h1>The Doppler Effect</h1>
      <p>What is Doppler Shift?</p>
    </div>
    <div class="col-md-4"></div>
  </div>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4" id="form">
      <%= form_tag doppler_shift_doppler_shift_path do %>
          <%= label_tag('Velocity:') %> </br>
          <%= text_field_tag(:velocity) %>
          <%= select_tag(:units, options_for_select([['m/s', 1], ['mph', 2], ['kph', 3], ['beta', 4]])) %> </br>
          <%= label_tag('Frequency:') %> </br>
          <%= text_field_tag(:delta_t) %> s </br>
          <%= submit_tag 'Shift' %> </br>
          <%= text_field_tag('answer', @dt_p) %>
      <% end %>
    </div>
    <div class="col-md-4"></div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8" id="black_box">
      <p><input type="button" value="Click Me" id="ToggleMe1a" /></p>
      <p id="ToggleMe1b">
        The formula for Time Dilation is
        $$t=\frac{t_0}{\sqrt{1-\beta^2}}$$

        You asked, "if I travel at a speed of <%= params[:velocity] %>
        <%= @u %>
        for <%= params[:delta_t] %>, how much time will pass
        in a stationary frame.

        Plug the values you inputted into the given formula for Time Dilation.
        $$t=\frac{<%= params[:delta_t] %>}{\sqrt{1-<%= @b %>^2}}=<%= @dt_p %>$$
      </p>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $("#ToggleMe1a").click(function() {
            $("#ToggleMe1b").toggle();
        });
    });
</script>

</body>

app/views/index/index.html.erb
<head xmlns="http://www.w3.org/1999/html">

  <%= stylesheet_link_tag "application" %>

  <title>The Physics Machine</title>
</head>


<body>
<div class="container">
  <div class="row" id="top_row">   <!-- Top Row -->
    <div class="col-md-12"></div>
  </div>
  <div class="row" id="second_row">                     <!-- 2nd row -->
    <div class="col-md-3">MATH</div>
    <div class="col-md-3" id="physics_logo">
      PHYSICS
    </div>
    <div class="col-md-3">ASTRONOMY</div>
    <div class="col-md-3">CHEMISTRY</div>
  </div>
  <div class="row">                     <!-- Middle Row -->
    <div class="col-md-12" id="main_title">
      <%= image_tag("main_title_bar_code.png") %>
    </div>
  </div>
  <div class="row">                     <!-- 4th Row -->
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
  </div>
  <div class="row" id="main_bottom_row">    <!-- Bottom Row -->
    <div class="col-md-12"></div>
  </div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThePhysicsMachine03</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <%= javascript_include_tag "http://code.highcharts.com/highcharts.js", "chartkick" %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/length_contraction/length_contraction.html.erb
<head xmlns="http://www.w3.org/1999/html">

  <title>Time Dilation</title>
</head>

<h1>Length Contraction</h1>
<p>What is Length Contraction?</p>

<%= form_tag(length_contraction_length_contraction_path) do %>
    <%= label_tag('Velocity:') %>
    <%= text_field_tag(:velocity) %>
    <%= select_tag(:units, options_for_select([['m/s', 1], ['mph', 2], ['kph', 3], ['beta', 4]])) %>
    <%= label_tag('Length:') %>
    <%= text_field_tag(:length) %>
    <%= submit_tag 'Contract' %>
    <%= text_field_tag('answer', @dl) %>
<% end %>

app/views/main/main.html.erb
<head xmlns="http://www.w3.org/1999/html">

  <%= stylesheet_link_tag "application" %>

  <title>The Physics Machine</title>
</head>


<body>
<div class="container">
  <div class="row" id="top_row">   <!-- Top Row -->
    <div class="col-md-12"></div>
  </div>
  <div class="row" id="second_row">                     <!-- 2nd row -->
    <div class="col-md-2"></div>
    <div class="col-md-6"></div>
    <div class="col-md-2"></div>
  </div>
  <div class="row">                     <!-- Middle Row -->
    <div class="col-md-12" id="main_title">
      <%= link_to "/index/index" do
        image_tag("main_title_bar_code.png",
                  onmouseover: "this.src='#{asset_path('main_title_bar_code_hover.png')}'",
                  onmouseout: "this.src='#{asset_path('main_title_bar_code.png')}'")
      end %>
    </div>
  </div>
  <div class="row">                     <!-- 4th Row -->
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
  </div>
  <div class="row" id="main_bottom_row">    <!-- Bottom Row -->
    <div class="col-md-12"></div>
  </div>
</div>
</body>

app/views/projectile/free_fall.html.erb
<head xmlns="http://www.w3.org/1999/html">

  <title>Time Dilation</title>
</head>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Free Fall</h1>
      <p>Free fall motion explanation</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6" id="free_fall_form">
      <%= form_tag(projectile_free_fall_path) do %>
        <%= label_tag('Starting value of x (m):') %>
        <%= text_field_tag(:x_0) %></br>
        <%= label_tag('Initial velocity (m/s):') %>
        <%= text_field_tag(:v_0) %></br>
        <%= label_tag('Starting time (usually 0) (s):') %>
        <%= text_field_tag(:t_0) %></br>
        <%= submit_tag 'Compute' %></br>
        <%= label_tag('Time it takes to hit the ground (s):') %></br>
        <%= text_field_tag('answer', @hit.round(2)) %>
      <% end %>
    </div>
    <div class="col-md-6"></div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= high_chart("some_id", @graph) %>
    </div>
    <div class="col-md-6">
      <table class="table table-striped">
        <tr>
          <td>Time (s)</td>
          <td>Height (m)</td>
        </tr>
        <% @x_t.each do |x| %>
            <tr>
              <td><%= x[0] %></td>
              <td><%= x[1] %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/projectile/projectile.html.erb
<head xmlns="http://www.w3.org/1999/html">

  <title>Time Dilation</title>
</head>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Projectile Motion</h1>
      <p>Projectile motion explanation</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <p>
      Projectile motion is something that can be described
      by Physics. Projectile motion is something that can be described
      by Physics. Projectile motion is something that can be described
      by Physics. Projectile motion is something that can be described
      by Physics. Projectile motion is something that can be described
      by Physics. Projectile motion is something that can be described
      by Physics. Projectile motion is something that can be described
      by Physics. Projectile motion is something that can be described
      by Physics.
      </p>
    </div>
    <div class="col-md-8" id="free_fall_form">
      <%= form_tag(projectile_projectile_path) do %>
        <%= label_tag('Starting value of x (m):') %>
        <%= text_field_tag(:x_0) %></br>
        <%= label_tag('Starting value of y (m):') %>
        <%= text_field_tag(:y_0) %></br>
        <%= label_tag('Initial velocity (m/s):') %>
        <%= text_field_tag(:v_0) %></br>
        <%= label_tag('Angle (rad):') %>
        <%= text_field_tag(:angle) %></br>
        <%= submit_tag 'Compute' %></br>
        <%= label_tag('Maximum height (m):') %>
        <%= text_field_tag('answer', @y_max.round(2)) %></br>
        <%= label_tag('Maximum range (m):') %>
        <%= text_field_tag('answer', @distance.round(2)) %></br>
        <%= label_tag('Time of flight (s):') %>
        <%= text_field_tag('answer', @tof.round(2)) %></br>
          <%= label_tag('Time of flight general (s):') %>
          <%= text_field_tag('answer', @tof_gen.round(2)) %></br>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= high_chart("some_id", @graph) %>
    </div>
    <div class="col-md-6">

    </div>
  </div>
</div>

app/views/time_dilation/time_dilation.html.erb
<head xmlns="http://www.w3.org/1999/html">

<%= stylesheet_link_tag "time_dilation.css.scss" %>

<title>Time Dilation</title>
</head>

<body>
<div class="container">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <h1>Time Dilation</h1>
        <p>What is Time Dilation?</p>
      </div>
      <div class="col-md-4"></div>
    </div>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4" id="form">
        <%= form_tag time_dilation_time_dilation_path do %>
          <%= label_tag('Velocity:') %> </br>
          <%= text_field_tag(:velocity) %>
          <%= select_tag(:units, options_for_select([['m/s', 1], ['mph', 2], ['kph', 3], ['beta', 4]])) %> </br>
          <%= label_tag('Time:') %> </br>
          <%= text_field_tag(:delta_t) %> s </br>
          <%= submit_tag 'Dilate' %> </br>
          <%= text_field_tag('answer', @dt_p) %>
        <% end %>
      </div>
      <div class="col-md-4"></div>
    </div>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8" id="black_box">
        <p><input type="button" value="Click Me" id="ToggleMe1a" /></p>
        <p id="ToggleMe1b">
          The formula for Time Dilation is
          $$t=\frac{t_0}{\sqrt{1-\beta^2}}$$

          You asked, "if I travel at a speed of <%= params[:velocity] %>
          <%= @u %>
          for <%= params[:delta_t] %>, how much time will pass
          in a stationary frame.

          Plug the values you inputted into the given formula for Time Dilation.
          $$t=\frac{<%= params[:delta_t] %>}{\sqrt{1-<%= @b %>^2}}=<%= @dt_p %>$$
        </p>
      </div>
      <div class="col-md-2"></div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $("#ToggleMe1a").click(function() {
            $("#ToggleMe1b").toggle();
        });
    });
</script>

</body>

app/views/universe_history/universe_history.html.erb
<head xmlns="http://www.w3.org/1999/html">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

  <%= stylesheet_link_tag "time_dilation.css.scss" %>

  <title>Time Dilation</title>
</head>

<body>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active" style="align-content: center">
      <%= image_tag("Planck_full_rbcol_sm.png") %>
      <div class="carousel-caption">
        <h1>The Big Bang</h1>
      </div>
    </div>

    <div class="item">
      <img src="img_chania2.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="img_flower.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="img_flower2.jpg" alt="Flower">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</body>